---

- name: Add RabbitMQ cluster hosts to /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^{{ item.ip }}\s+{{ item.name }}$'
    line: '{{ item.ip }} {{ item.name }}'
  loop: "{{ rabbitmq_hosts }}"

