---

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: Stop RabbitMQ
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: stopped
      
- name: Download .erlang.cookie from rmq-1
  fetch:
    src: /var/lib/rabbitmq/.erlang.cookie
    dest: files/erlang.cookie
    flat: yes
  when: inventory_hostname == "rmq-1"


- name: Replace .erlang.cookie with .cookie from rmq-1
  copy:
    src: files/erlang.cookie
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: '0400'
  when: inventory_hostname != "rmq-1"

- name: Restart RabbitMQ 
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
