---

- name: install postgres
  ansible.builtin.apt:
    name: postgresql
    state: latest

- name: install python dependencies
  ansible.builtin.apt:
    name: [libpq-dev, python3-dev]
    state: latest

- name: install psycopg2-binary
  ansible.builtin.apt:
    name: python3-psycopg2
    state: latest

- name: check postgres running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
